use_frameworks!
platform :ios, '10.0'

flutter_application_path = './../../zg_erp_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterUnitTest_Example' do
  pod 'FlutterUnitTest', :path => '../'

  install_all_flutter_pods(flutter_application_path)

  target 'FlutterUnitTest_Tests' do
    inherit! :search_paths
  end
end
